tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        // Current Light Theme Colors (Updated to New Blue & Teal Palette)
        "primary-fixed": "#d5e3ff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e7f9ee",
        "background": "#f9fcfb",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9fcfb",
        "on-tertiary-container": "#9b9c9c",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-tint": "#2680FF",
        "primary-fixed-dim": "#a7c8ff",
        "surface-dim": "#dadada",
        "secondary-fixed-dim": "#15C05A",
        "surface-container-low": "#f3f6f5",
        "outline": "#737780",
        "primary": "#2680FF",
        "on-primary-fixed": "#001b3c",
        "surface-container-highest": "#e2e7e5",
        "error": "#ba1a1a",
        "on-background": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "on-secondary-container": "#003d1a",
        "on-primary-fixed-variant": "#1f477b",
        "tertiary-fixed": "#e2e2e2",
        "outline-variant": "#c3c6d1",
        "surface": "#f9fcfb",
        "on-secondary-fixed": "#00210e",
        "primary-container": "#e6f0ff",
        "surface-container": "#edf2f0",
        "inverse-surface": "#2f3131",
        "tertiary-container": "#323434",
        "surface-container-high": "#e8edeb",
        "on-surface-variant": "#43474f",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e2e7e5",
        "on-primary": "#ffffff",
        "secondary": "#15C05A",
        "on-secondary": "#ffffff",
        "inverse-primary": "#a7c8ff",
        "on-error": "#ffffff",
        "tertiary": "#1d1f1f",
        "on-primary-container": "#0047a3",
        "on-secondary-fixed-variant": "#005226",
        "secondary-container": "#c9f3d9",
        "on-surface": "#1a1c1c",
        "on-tertiary-fixed": "#1a1c1c",
        "on-error-container": "#93000a",

        // Abyssal Elegance Dark Theme Colors (Abyss Collection)
        "abyss": {
          "surface": "#0a141d",
          "surface-dim": "#0a141d",
          "surface-bright": "#313a44",
          "container-lowest": "#060f17",
          "container-low": "#131d25",
          "container": "#172129",
          "container-high": "#212b34",
          "container-highest": "#2c363f",
          "on-surface": "#dae3f0",
          "on-variant": "#c4c6ce",
          "outline": "#8e9198",
          "outline-variant": "#43474d",
          "primary": "#b1c8e9",
          "on-primary": "#1a324c",
          "primary-container": "#001a33",
          "on-primary-container": "#6d84a2",
          "secondary": "#ffb59c", // Coral Orange
          "on-secondary": "#5c1a00",
          "secondary-container": "#8e2c01",
          "on-secondary-container": "#ffaa8d",
          "tertiary": "#bec6e0",
          "tertiary-container": "#11192c",
          "background": "#0a141d"
        }
      },
      "borderRadius": {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "container-max": "1280px",
        "gutter": "24px"
      },
      "fontFamily": {
        "h1": ["Epilogue"],
        "body": ["Epilogue"],
        "label": ["Epilogue"]
      },
      "fontSize": {
        "display-xl": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700" }]
      }
    },
  },
}
